version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=minor
      #- MONGO_DATA_DIR: /data/db
      #- MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    #command: mongod --smallfiles --logpath=/dev/null # --quiet
  airpay-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
    #container_name: 'airplay-api'
    restart: 'always' #on-failure
    #depends_on:
    #  - db
    #expose:
    #  - '4100'
    #ports:
    #  - '4100:4100'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - api_network
      - postgres_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airpay.entrypoints=websecure"
      - "traefik.http.routers.airpay.rule=Host(`airpay-api.minorfoodit.com`)"
      - "traefik.http.routers.airpay.service=airpay-api"
      - "traefik.http.routers.airpay.tls=true"
      - "traefik.http.services.airpay-api.loadbalancer.server.port=4100"
      - "traefik.docker.network=api_network"

networks:
  postgres_network:
    external: true
  api_network:
    external: true